SRC=humain1.c humain2.c humain3.c 1-avaltoname.c 2-legende.c 3-avalam2i.c 4-yazur.c 5-vroum.c 6-alexa.c 7-aya.c 8-botabdul.c 9-mark4.c 10-chomage.c 11-neotheone.c 12-shao.c 13-ig22qi.c 14-kantaou2i.c 15-binks.c 16-jarvis.c 17-tsavalam.c 14-kantaou2i-2.c 14-kantaou2i-blitz.c 9-mark5.c 5-vroum-2.c 3-avalam2i-2.c kantalam2i.c kantalam2i-2.c alexandre.c

